# Generated by Django 4.1.5 on 2023-01-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='weight',
        ),
    ]
