# Generated by Django 4.1.5 on 2023-02-04 11:15

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Header text.', max_length=80)),
                ('heading_text', models.TextField(help_text='Heading text', max_length=255)),
                ('font_photo', models.ImageField(upload_to=main_page.models.AboutUs.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='BlockOfInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.SmallIntegerField()),
                ('block_title', models.TextField(max_length=50)),
                ('block_text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_description', models.TextField(max_length=255)),
                ('member_photo', models.ImageField(upload_to=main_page.models.CrewMember.get_file_name)),
                ('twitter_link', models.URLField(help_text='Input here URL to Twitter account.')),
                ('facebook_link', models.URLField(help_text='Input here URL to Facebook account.')),
                ('instagram_link', models.URLField(help_text='Input here URL to Instagram account.')),
                ('linkedin_link', models.URLField(help_text='Input here URL to LinkedIn account.')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('customer_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, unique=True)),
                ('event_description', models.TextField(max_length=500)),
                ('event_date_and_time', models.DateTimeField(help_text='Enter date and time of event')),
                ('event_price', models.SmallIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to=main_page.models.Events.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('event_date_and_time',),
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.HeroSection.get_file_name)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(help_text='Header text.', max_length=80)),
                ('heading_text', models.TextField(help_text='Heading text', max_length=255)),
                ('video', models.URLField(blank=True, help_text='Paste here URL to the video.')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoToGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.PhotoToGallery.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('is_visible',),
            },
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='weight',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.Dishes.get_file_name),
        ),
    ]
