# Generated by Django 4.1.5 on 2023-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_aboutus_blockofinformation_crewmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(default='test', help_text='Enter here link to the video.'),
            preserve_default=False,
        ),
    ]
