# Generated by Django 4.1.5 on 2023-01-30 08:20

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_dishes_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.Dishes.get_file_name),
        ),
    ]
