# Generated by Django 4.1.5 on 2023-02-04 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_aboutus_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(message='Standard e-mail form', regex='^[a-zA-Z0-9]{1}[a-zA-Z0-9_]+(-{1})?[a-zA-Z0-9_]+@{1}([a-zA-Z0-9]+\\.)+[a-z0-9]{1}([a-z0-9-]*[a-z0-9])?$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(/d{3}[- .]?){2}/d{4}$')])),
                ('date_reservation', models.DateField(auto_now=True)),
                ('time_reservation', models.TimeField()),
                ('persons', models.PositiveSmallIntegerField()),
                ('message', models.TimeField(blank=True, max_length=250)),
                ('date_of_the_request', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_of_the_request',),
            },
        ),
        migrations.DeleteModel(
            name='HomeSliderInfo',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading_text',
            field=models.TextField(help_text='Heading text', max_length=700),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='member_description',
            field=models.CharField(max_length=80),
        ),
    ]
