# Generated by Django 4.1.5 on 2023-01-31 11:21

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_dishes_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Header text.', max_length=80)),
                ('heading_text', models.TextField(help_text='Heading text', max_length=255)),
                ('font_photo', models.ImageField(upload_to=main_page.models.AboutUs.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='CrewBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80)),
                ('heading_text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('customer_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, unique=True)),
                ('event_description', models.CharField(max_length=500)),
                ('event_date_and_time', models.DateTimeField(help_text='Enter date and time of event')),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='HomeSliderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Header text.', max_length=80)),
                ('heading_text', models.TextField(help_text='Heading text', max_length=255)),
                ('video', models.URLField(blank=True, help_text='Paste here URL to the video.')),
            ],
        ),
        migrations.CreateModel(
            name='InformationInBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80)),
                ('heading_text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of reservation.')),
                ('time', models.TimeField(help_text='Time of reservation.')),
                ('name_of_customer', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=65)),
                ('phone_number', models.CharField(max_length=20)),
                ('number_of_people', models.SmallIntegerField()),
                ('additional_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to=main_page.models.Photo.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.gallery')),
            ],
            options={
                'ordering': ('position', 'gallery'),
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_description', models.TextField(max_length=255)),
                ('member_photo', models.ImageField(upload_to=main_page.models.CrewMember.get_file_name)),
                ('twitter_link', models.URLField(help_text='Input here URL to Twitter account.')),
                ('facebook_link', models.URLField(help_text='Input here URL to Facebook account.')),
                ('instagram_link', models.URLField(help_text='Input here URL to Instagram account.')),
                ('linkedin_link', models.URLField(help_text='Input here URL to LinkedIn account.')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.crewblock')),
            ],
        ),
        migrations.CreateModel(
            name='BlockOfInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.SmallIntegerField()),
                ('block_title', models.CharField(max_length=50)),
                ('block_text', models.TextField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.informationinblocks')),
            ],
        ),
    ]
