# Generated by Django 4.1.5 on 2023-01-31 11:32

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_aboutus_crewblock_customerfeedback_events_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.Events.get_file_name),
        ),
    ]
