# Generated by Django 4.1.5 on 2023-02-04 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_userreservation_delete_homesliderinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='message',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')]),
        ),
    ]
