# Generated by Django 4.1.5 on 2023-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_userreservation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date_reservation',
            field=models.DateField(),
        ),
    ]
