# Generated by Django 4.1.5 on 2023-02-07 10:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_userreservation_date_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThisIsForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_is_text', tinymce.models.HTMLField(max_length=250)),
                ('this_is_text_2', tinymce.models.HTMLField(max_length=250)),
                ('this_is_text_3', tinymce.models.HTMLField(max_length=250)),
            ],
        ),
    ]
