# Generated by Django 4.1.5 on 2023-02-07 11:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationInContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('heading_text', tinymce.models.HTMLField(max_length=250)),
                ('location', tinymce.models.HTMLField()),
                ('open_hours', tinymce.models.HTMLField()),
                ('email', tinymce.models.HTMLField()),
                ('call', tinymce.models.HTMLField()),
            ],
        ),
    ]
