# Generated by Django 4.1.5 on 2023-02-07 12:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_informationincontactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', tinymce.models.HTMLField()),
                ('heading_text', tinymce.models.HTMLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=500)),
                ('instagram', models.CharField(blank=True, max_length=500)),
                ('skype', models.CharField(blank=True, max_length=500)),
                ('linked_in', models.CharField(blank=True, max_length=500)),
                ('site_owner', tinymce.models.HTMLField()),
            ],
        ),
    ]
