# Generated by Django 4.1.5 on 2023-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_informationincontactus_open_hours_for_top_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationincontactus',
            name='open_hours_for_top_bar',
            field=models.CharField(max_length=40),
        ),
    ]
